name: core_model
description: Core data classes
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=3.10.4"

dependencies:
  # SDK extensions
  collection: any
  meta: any

dev_dependencies:
  lints_tool:
    path: ../../tool/lints_tool
