# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"

  - package-ecosystem: "pub"
    directory: "/packages/model/core_model" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"

  - package-ecosystem: "pub"
    directory: "/packages/model/auth_model" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"

  - package-ecosystem: "pub"
    directory: "/packages/model/grpc_model" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"

  - package-ecosystem: "pub"
    directory: "/packages/tool/core_tool" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"

  - package-ecosystem: "pub"
    directory: "/packages/tool/ui_tool" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"

  - package-ecosystem: "pub"
    directory: "/packages/tool/converter/json_converter" # Location of package manifests
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: /
    target-branch: "main"
