name: core_tool

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.4"

dependencies:
  # SDK extensions
  meta: any
  collection: any
  characters: any
  uuid: any

  # Internationalization
  intl: any

dev_dependencies:
  lints_tool:
    path: ../../tool/lints_tool
