name: auth_model
resolution: workspace

description: Authentication model

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  # Packages
  core_model:
    path: ../../model/core_model
  grpc_model:
    path: ../../model/grpc_model
  json_converter:
    path: ../../tool/converter/json_converter

  # SDK extensions
  collection: any
  meta: any
  uuid: any
  fixnum: any
  async: any
  crypto: any

  # Internationalization
  intl: any

  # Code generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # API
  grpc: ^5.1.0
  protobuf: ^6.0.0
  retry: ^3.1.2

dev_dependencies:
  # Code generation
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

  # Lints
  lints_tool:
    path: ../../tool/lints_tool
